[tools]
biome = "2.4.10"
hk = "1.57.0"
pkl = "0.32.1"

[settings]
env_shell_expand = true

[tasks.check]
description = "Run all checks"
run = "hk check"

[tasks.fix]
description = "Run all fixers and formatters"
run = "hk fix"
